<?php

/**
 * @file
 * Demo module, Basic Ajax form submit (Ajax framework).
 */

 /**
  * Implements hook_menu().
  */
function ajax_form_pro_menu() {
    $items['ajax/demo_form'] = array(
      'page callback' => 'drupal_get_form',
      'page arguments' => array('ajax_demo_form'),
      'access callback' => TRUE,
      'type' => MENU_CALLBACK,
      'file' => 'includes/ajax_demo.inc',
    );
      $items['address'] = array(
      'page callback' => 'drupal_get_form',
      'page arguments' => array('ajax_states_demo'),
      'access callback' => TRUE,
      'type' => MENU_CALLBACK,
      'file' => 'includes/ajax_states_demo.inc',
    );
       $items['hash_state'] = array(
      'page callback' => 'drupal_get_form',
      'page arguments' => array('hash_states_demo'),
      'access callback' => TRUE,
      'type' => MENU_CALLBACK,
      'file' => 'includes/hash_states_demo.inc',
    );
        $items['ajax_submit'] = array(
      'page callback' => 'drupal_get_form',
      'page arguments' => array('ajax_submit_demo'),
      'access callback' => TRUE,
      'type' => MENU_CALLBACK,
      'file' => 'includes/ajax_submit_demo.inc',
    );
      $items['display/mytheme'] = array(
      'page callback' => 'new_theme_callback',
      'access callback' => TRUE,
      'type' => MENU_CALLBACK,
      'file' => 'includes/hook_theme_demo.inc',
    );
      $items['ajax/dependent'] = array(
      'page callback' => 'drupal_get_form',
      'page arguments' => array('ajax_dependent_demo'),
      'access callback' => TRUE,
      'type' => MENU_CALLBACK,
      'file' => 'includes/ajax_dependent_demo.inc',
    );
      $items['ajax/demo'] = array(
      'page callback' => 'drupal_get_form',
      'page arguments' => array('ajax_display_form'),
      'access callback' => TRUE,
      'type' => MENU_CALLBACK,
      'file' => 'includes/ajax_displayform.inc',
    );
      $items['ajax/autofill'] = array(
      'page callback' => 'drupal_get_form',
      'page arguments' => array('ajax_address_demo'),
      'access callback' => TRUE,
      'type' => MENU_CALLBACK,
      'file' => 'includes/ajax_address_demo.inc',
    );
    return $items;
}
